# Generated by Django 5.0.6 on 2024-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
